name: Hello World Workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/hello-world-template.yml  # Call the reusable workflow
