name: Conditional Job Workflow

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Select which job to run'
        required: true
        default: 'job1'
        type: choice
        options:
          - job1
          - job2
          - job3

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'job1' }}
    steps:
      - name: Run Job 1
        run: echo "Running Job 1"

  job2:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'job2' }}
    steps:
      - name: Run Job 2
        run: echo "Running Job 2"

  job3:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'job3' }}
    steps:
      - name: Run Job 3
        run: echo "Running Job 3"
