name: Example Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print input values
        run: |
          echo "Deploying to environment: ${{ inputs.environment }}"
          echo "Debug mode: ${{ inputs.debug }}"
